defaults:
  - datamodule
  - model
  - wandb

# Example datamodule configuration
datamodule:
  _target_: src.datamodules.cloudsat_multi_dataloader.CloudSatMultiDataModule
  data_dir_dict:
    msg_cloudsat: /mnt/e/Data/3DClouds/fine-tuning-reprocessed/cloudsat-msg-paired/
    goes_cloudsat: /mnt/e/Data/3DClouds/fine-tuning-reprocessed/cloudsat-goes-paired/
    himawari_cloudsat: /mnt/e/Data/3DClouds/fine-tuning-reprocessed/cloudsat-himawari-paired/
  transforms_dict: {}
  batch_size: 8
  num_workers: 8
  pin_memory: false
  prefetch_factor: 2
  load_overpass_mask: true
  cloudsat_variables: ['IWC']
